vault_ssh_secret_backend_role: add algorithm_signer argument
terraform-providers/terraform-provider-vault pull request #809
Opened 2020-07-05 13:29 UTC by andreaso

The `algorithm_signer` argument was introduced in Vault 1.4.3. See also https://github.com/hashicorp/vault/pull/9096.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

###  Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-vault/blob/master/CHANGELOG.md):

```release-note
resource/vault_ssh_secret_backend_role: Support new `algorithm_signer` argument
```

### Output from acceptance testing:

```
$ TESTARGS="--run SSHSecretBackendRole" make testacc
...
=== RUN   TestAccSSHSecretBackendRole_basic
--- PASS: TestAccSSHSecretBackendRole_basic (0.27s)
=== RUN   TestAccSSHSecretBackendRoleOTP_basic
--- PASS: TestAccSSHSecretBackendRoleOTP_basic (0.16s)
=== RUN   TestAccSSHSecretBackendRole_import
--- PASS: TestAccSSHSecretBackendRole_import (0.18s)
...
```

2020-07-20 17:05 UTC, andreaso commented
Hello @catsby. It was suggested in #vault-tool that I might want to ping you about this PR.

2020-10-09 22:02 UTC, catsby requested changes
Sorry for the delay in review! I think we need to remove the `Default` at this time. Perhaps when this was originally opened the default was true, but I believe with https://github.com/hashicorp/vault/pull/9824 that's not longer the case (and the docs on vaultproject.io need to be updated, I think)

2020-10-09 22:02 UTC, catsby commented on vault/resource_ssh_secret_backend_role.go
> +				Default:  "ssh-rsa",
I think we need to leave `algorithm_signer` as `Optional: true` and `Computed: true` and remove the default. The documentation on vaultproject.io says `ssh-rsa` is the default, but I believe that's not actually the case anymore. The API is returning `""` now and not returning any defaults

2020-10-12 21:08 UTC, catsby commented
Thank you for contributing! I made minor updates to account for the `ssh-rsa` no longer being a default, and I'm going to pull this in now. Thanks!

2020-10-12 21:08 UTC, merged

2020-10-17 07:27 UTC, andreaso commented
Thanks!

Any best guest on when there will be a new release of the provider?